---
- hosts: 172.31.7.72
  become: yes
  tasks:
  - name: i want to execute linux command directory
    command: hostname  -f
    register: myresult
  - name: i want to debug
    debug: 
       msg: "{{myresult}}"
       
