---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install webserver on ubuntu 16 nodes
    apt:
      name: "{{mywebpackageonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: i want to start webserver on ubuntu 16 nodes
    service: 
       name: "{{mywebpackageonubuntu}}"
       state: started
    when: ansible_os_family =="Debian"
  - name: i want to install webserver on Redhatnode
    yum: 
      name: "{{mywebpackageonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: i want to start webserver on RedHatnode
    service: 
       name: "{{mywebpackageonredhat}}"
       state: started
    when: ansible_os_family =="RedHat"


    