---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install webserver on ubuntu 16 nodes
    apt:
      name: "{{mywebpackageonubuntu=apache2}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: i want to start webserver on ubuntu 16 nodes
    service: 
       name: "{{mywebpackageonubuntu=apache2}}"
       state: started
    when: ansible_os_family =="Debian"
  - name: i want to install webserver on Redhat node
    yum: 
      name: "{{mywebpackageonredhat=httpd}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: i want to start webserver on RedHat node
    service: 
       name: "{{mywebpackageonredhat=httpd}}"
       state: started
    when: ansible_os_family =="RedHat"


    